### ISSUE TITLE
同步歌词

### ISSUE THREAD

**Issue by Qusic** [GyrosWorkshop/WukongWeb#10]

**Comment by Senorsen** [comment]
Interface: 
- [ISong.lyrics: ILyric[]](https://github.com/GyrosWorkshop/Wukong/blob/9e674a43f8dd0aba63b2dceac185ad746417fe97/README.md#song)
- [lyricss: ILyric[]](https://github.com/GyrosWorkshop/Wukong/blob/9e674a43f8dd0aba63b2dceac185ad746417fe97/README.md#lyrics)

ref.

@xuchaoying @Qusic
