### ISSUE TITLE
添加歌曲的时候没有反馈

### ISSUE THREAD

**Issue by dayjoyx** [GyrosWorkshop/WukongWeb#31]
不知道有没有添上,页面也没有动,可以加个toast之类的吧

**Comment by richard1122** [comment]
@Qusic 后端将对 UpdateNextSong 返回状态码以表示这首歌在 provider 中获取失败

**Comment by richard1122** [comment]
也许可以提前做一些错误提示

**Comment by richard1122** [comment]
不是这个 issue 的意思，见 https://github.com/GyrosWorkshop/WukongWeb/issues/35
