### ISSUE TITLE
Make Windows happy

### ISSUE THREAD

**Issue by aoli-al** [GyrosWorkshop/WukongWeb#38]
'env' is not recognized as an internal or external command,
operable program or batch file.

http://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-in-windows

**Comment by Qusic** [comment]
npm scripts `package` 和 `clean` 好像也不太能在windows上用，之前没有`env`直接写变量，森森说windows不支持，加了`env`可以在cygwin下用好像。

我打算看看把环境变量去掉吧，看看能不能都在js里处理，这样更能跨平台点

**Comment by Senorsen** [comment]
Use git bash or wsl

**Comment by aoli-al** [comment]
node is not really working with wsl. I'm using windows 10 stable, it will crash when I do npm start.

**Comment by Senorsen** [comment]
What about Git Bash?

**Comment by aoli-al** [comment]
Nobody is using git bash.

**Comment by Qusic** [comment]
我初步打算用一下这个
https://github.com/dthree/cash

但是如果把环境变量放参数里那指定服务器就比较麻烦。。npm scripts好像没法加用户参数？

**Comment by Senorsen** [comment]
```
npm run someScript -- argv0 argv1 ...
npm run someScript argv0 argv1 ...
```

**Comment by Qusic** [comment]
或者继续用环境变量
https://github.com/kentcdodds/cross-env

**Comment by aoli-al** [comment]
那个cross-env看起来可以。。。

**Comment by aoli-al** [comment]
他们最后逼用户下了一个git bash （（

**Comment by Qusic** [comment]
我们没有逼用户，用户不需要git bash也能用

**Comment by aoli-al** [comment]
你们没有用户（（

**Comment by Senorsen** [comment]
你不是用户，你是开发者

**Comment by aoli-al** [comment]
既然wsl用不了了。。。

**Comment by Senorsen** [comment]
Use this to change your life: 
https://git-scm.com/download/win
