### ISSUE TITLE
能否在同步歌单时增量更新？

### ISSUE THREAD

**Issue by Senorsen** [GyrosWorkshop/WukongWeb#39]
具体是指，在同步歌单时，增加一个同步选项，使得：

1. 对于“云端”歌单中多出的歌曲，按原本顺序增加在 wukong 播放列表的最上方；
2. （可能实现难或有歧义，可暂时搁置）“云端”歌单中删除的歌曲，wukong 播放列表也删除对应歌曲。

这样的好处是：wukong 播放列表原本是随机后的歌单，用户想同步后先播放最近增加的新歌曲，然后再播放原本打乱的歌曲。

**Comment by Qusic** [comment]
可以 不过有必要弄成选项吗 默认就这样的行为好像也没问题？

**Comment by Senorsen** [comment]
好像有点问题，因为有的时候可能希望全量更新，有的时候想增量更新，不好说

**Comment by Qusic** [comment]
我觉得这样分两种同步方式很迷惑用户
可以用另一种方式实现
搜索框贴一个歌单链接可以列出歌单
然后再实现某种批量添加删除的交互流程

**Comment by Senorsen** [comment]
嗯，刚刚我也想到，可以添加一个“高级”的批量删除操作。这样就可以在不损失原有功能的基础上，有增量更新歌单的功能。
