### ISSUE TITLE
WSL 没办法运行

### ISSUE THREAD

**Issue by aoli-al** [GyrosWorkshop/WukongWeb#43]
`node -v`
v7.9.0

`npm start`

ERROR in ./src/entry.js
Module not found: Error: Can't resolve 'react-hot-loader' in '/mnt/c/Users/Leo/Source/Repos/WukongWeb/src'
 @ ./src/entry.js 18:21-48
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack/hot/only-dev-server webpack-dev-server/client?http://localhost:8080 ./entry

**Comment by Qusic** [comment]
错误说你有个包没装好
npm -g i npm
要不要升级一下npm重新装了看看

**Comment by aoli-al** [comment]
是不是可以提供一个docker镜像，这样我们本地部署也方便?

**Comment by Qusic** [comment]
支持yarn了 你试试yarn？

**Comment by aoli-al** [comment]
@Qusic yarn可以用！
