### ISSUE TITLE
以后接入 SignalR。

### ISSUE THREAD

**Issue by richard1122** [GyrosWorkshop/WukongWeb#6]
> Incredibly simple real-time web for .NET

https://github.com/aspnet/SignalR-Server
https://github.com/aspnet/SignalR-Client-JS
client 还 under active development.

**Comment by richard1122** [comment]
其实有个依赖 jquery的client。

**Comment by Senorsen** [comment]
😢

**Comment by Qusic** [comment]
那等以后到了再说（
