### ISSUE TITLE
教 Firefox 读中文

### ISSUE THREAD

**Issue by aoli-al** [GyrosWorkshop/WukongWeb#69]
现在还读不出来。。。

**Comment by Qusic** [comment]
应该是浏览器调的操作系统的tts，你是啥语言的啥操作系统

**Comment by aoli-al** [comment]
我4英文的操作系统。。。

**Comment by Qusic** [comment]
那我猜这个应该有用： https://support.office.com/en-us/article/download-voices-for-immersive-reader-read-mode-and-read-aloud-4c83a8d8-7486-42f7-8e46-2b0fdf753130

**Comment by aoli-al** [comment]
那我是fedora。。。

**Comment by Qusic** [comment]
那一个合格的linux用户不应该开出这种issue的
