### ISSUE TITLE
页面右侧滚动条被覆盖

### ISSUE THREAD

**Issue by Senorsen** [GyrosWorkshop/WukongWeb#9]
![image](https://cloud.githubusercontent.com/assets/4176091/18822942/61f49e4e-83e7-11e6-8f8e-8b7ccad51e6a.png)

**Comment by Qusic** [comment]
并没有什么科学的办法。。这个div就得放那么大。。据说也可以把滚动条往右挪出窗口，自己实现一个滚动条，但是比较黑（（

**Comment by Senorsen** [comment]
这个是可以解决的。。

**Comment by Qusic** [comment]
怎么解决

**Comment by Qusic** [comment]
我想的话 最好是能让滚动条开始的地方在topbar下面
这样往下滚滚动条往下，topbar往上变小，不会挡住

**Comment by Senorsen** [comment]
把滚动条交给整个网页而不是这个 div 怎么样？这是我先前接触过的惯常做法

**Comment by Qusic** [comment]
这样也可以，让滚动条就压着topbar？。。

**Comment by Senorsen** [comment]
对的
